[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "cd django_web_app",
  "python manage.py makemigrations",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "cd django_web_app && python manage.py migrate && gunicorn django_web_app.wsgi:application --bind 0.0.0.0:$PORT"
